### PR TITLE
Disable screenshot protection setting if the platform is linux

### LINKED ISSUE #336: Screenshot Protection Doesn't Work on Linux
I'm running Ubuntu Mate 17.04 and the latest version of the wallet. I can still take screenshots with no issues. I think it's an issue with electron, however, because https://electron.atom.io/docs/api/browser-window/ only has macOS and Windows listed for "win.setContentProtection(enable)".

### PR DESCRIPTION
**Pull request by krau612**
Because Electron doesn't have content protection on Linux, I think the screenshot protection settings button should be disabled on Linux. Users shouldn't be given an option that they may think provides some security if the option actually does nothing, it's misleading.

Resolves #336

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -177,6 +177,10 @@ function createWindow () {
     }
   ];
 
+  if (process.platform === "linux") {
+    template[0].submenu[2] = { label: "Screenshot Protection Not Available On Linux", enabled: false};
+  }
```
Comment (spresnal) [inline main.js]: I don't think this is the best way to go about it -- specifically i'm talking about referencing template element 0 & submenu element 2. If a submenu gets added before the screenshot label then this will cause unintended effects.

Would be preferred to call a method from line 153 that gets the appropriate screenshot label

**Comment by krau612** [comment]
Good call, thank you @spresnal . I created a function to get the proper label.

One issue though is that template[0].submenu[2] is still used in updateScreenshotProtectionItem().

**Comment by luciorubeens** [comment]
+5 👍🏻
